import image1 from "../assets/images/1.jpg";
import image2 from "../assets/images/2.jpg";
import image3 from "../assets/images/9.jpeg";
import image4 from "../assets/images/4.jpg";
import image5 from "../assets/images/5.jpg";
import image6 from "../assets/images/6.jpeg";
import image7 from "../assets/images/7.jpg";
import image8 from "../assets/images/8.jpg";
import image9 from "../assets/images/commercial1.jpg";
import image10 from "../assets/images/commercial2.jpg";
import image11 from "../assets/images/11.jpg";
import image12 from "../assets/images/IMG_1589.jpg";
import image13 from "../assets/images/15.png";
import image14 from "../assets/images/IMG_1649.jpg";
import image15 from "../assets/images/bakan1.png";
import image16 from "../assets/images/bakan2.png";
import image17 from "../assets/images/14.png";
import image18 from "../assets/images/10.png";
import image19 from "../assets/images/16.png";
import image20 from "../assets/images/13.png";
import image21 from "../assets/images/24.jpeg";
import image22 from "../assets/images/25.CR2.jpg";
import image23 from "../assets/images/26.jpg";
import image24 from "../assets/images/27.jpg";
import image25 from "../assets/images/28.jpg";
import image26 from "../assets/images/29.jpg";
import image27 from "../assets/images/32.jpg";
import image28 from "../assets/images/33.jpg";
import image29 from "../assets/images/34.jpg";
import image30 from "../assets/images/35.jpg";
import image31 from "../assets/images/36.jpg";
import image32 from "../assets/images/37.jpg";
import image33 from "../assets/images/38.jpg";
import image34 from "../assets/images/44.jpg";
import image35 from "../assets/images/45.jpg";
import image36 from "../assets/images/46.jpg";
import image37 from "../assets/images/23.JPG";
import image38 from "../assets/images/30.png";
import image39 from "../assets/images/31.JPG";
import image40 from "../assets/images/39.JPG";
import image41 from "../assets/images/40.JPG";
import image42 from "../assets/images/41.JPG";
import image43 from "../assets/images/42.JPG";
import image44 from "../assets/images/43.JPG";
import image45 from "../assets/images/48.JPG";
import image46 from "../assets/images/49.JPG";
import image47 from "../assets/images/47.jpg";
import image48 from "../assets/images/50.jpg";
import image49 from "../assets/images/51.jpg";
import image50 from "../assets/images/52.jpg";
import image51 from "../assets/images/53.jpg";
import image52 from "../assets/images/54.jpg";
import image53 from "../assets/images/55.jpg";
import image54 from "../assets/images/56.jpg";
import image55 from "../assets/images/57.jpg";
import image56 from "../assets/images/58.JPG";
import image57 from "../assets/images/60.png";
import image58 from "../assets/images/61.png";
import image59 from "../assets/images/62.png";
import image60 from "../assets/images/63.png";
import image61 from "../assets/images/64.png";
import image62 from "../assets/images/65.png";
import image63 from "../assets/images/66.png";
import image64 from "../assets/images/67.png";
import image65 from "../assets/images/68.png";
import image66 from "../assets/images/69.png";
import image67 from "../assets/images/70.png";
import image68 from "../assets/images/71.png";
import image69 from "../assets/images/72.png";
import image70 from "../assets/images/73.png";
import image71 from "../assets/images/74.png";
import image72 from "../assets/images/75.png";
import image73 from "../assets/images/76.png";
import image74 from "../assets/images/77.png";
import image75 from "../assets/images/78.png";
import image76 from "../assets/images/79.png";
import image77 from "../assets/images/80.png";
import image78 from "../assets/images/81.png";
import image79 from "../assets/images/82.png";
import image80 from "../assets/images/83.png";
import image81 from "../assets/images/84.png";
import image82 from "../assets/images/85.png";
import image83 from "../assets/images/90.png";

const imageData = [
  {
    id: 1,
    src: image1,
    alt: "Golden Acacia Dining Table",
    desc: "12' Dark Golden Acacia dining table in West Hampton",
    title: "Dark Acacia Dining Table",
    customer: "res",
    page: 1,
    type: "res-table",
  },
  {
    id: 2,
    src: image2,
    alt: "Golden Acacia Dining Table",
    desc: "30' Dark Golden Acacia dining table in New York City",
    title: "Golden Acacia Restaurant Table",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 3,
    src: image3,
    alt: "White Oak Side Table",
    desc: "24-Inch round side table with tapered legs",
    title: "White Oak Side Table",
    customer: "res",
    page: 1,
    type: "res-bed",
  },
  {
    id: 4,
    src: image4,
    alt: "Golden Acacia Decorative Slab",
    desc: "12' Golden Acacia slab displayed at a food hall in Salt Lake City",
    title: "Golden Acacia Decorative Slab",
    customer: "com",
    page: 1,
    type: "com-deco",
  },
  {
    id: 5,
    src: image5,
    alt: "30-Foot Golden Acacia Dining Table",
    desc: "30' Golden Acacia dining for a food hall in Salt Lake City, seats 50",
    title: "30-Foot Golden Acacia Dining Table",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 6,
    src: image6,
    alt: "Golden Acacia Dining Tables",
    desc: "Assortment of round Golden Acacia dining table in a food hall in Salt Lake City. The largest table is a giant Acacia root transformed into a table.",
    title: "Golden Acacia Dining Tables",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 7,
    src: image7,
    alt: "Fossilized Stone Tables",
    desc: "Fossilized stone tables made for a restaurant in Chicago",
    title: "Fossilized Stone Tables",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 8,
    src: image8,
    alt: "Golden Acacia Dining Table",
    desc: "10' Golden Acacia dining table for a residence in Chicago",
    title: "Golden Acacia Dining Table",
    customer: "res",
    page: 1,
    type: "res-table",
  },
  {
    id: 9,
    src: image9,
    alt: "66 Inch Solid White Oak Round",
    desc: "Sixty-six inch round table made out of solid white oak with a stone lazy suzan for a restaurant in Chicago",
    title: "66-Inch Solid White Oak Round",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 10,
    src: image10,
    alt: "8-Foot Solid White Oak Dining Table",
    desc: "This eight foot solid white oak dining table resides in a restaurant in downtown Chicago.",
    title: "8-Foot Solid White Oak Dining Table",
    customer: "com",
    page: 1,
    type: "com-table",
  },
  {
    id: 11,
    src: image11,
    alt: "Exotic Maka Wood Mirror",
    desc: "This mirror is surrounded with Maka wood that was recovered from the bottom of a river in Thailand.",
    title: "Exotic Maka Wood Mirror",
    customer: "res",
    page: 2,
    type: "res-deco",
  },
  {
    id: 12,
    src: image12,
    alt: "Ten Foot Ash Dining Table",
    desc: "This 10' table for a residence in northern Chicago features our intense black stain and custom legs all made from solid ash.",
    title: "Ten Foot Ash Dining Table",
    customer: "res",
    page: 2,
    type: "res-table",
  },
  {
    id: 13,
    src: image13,
    alt: "Eighty-Eight Inch Ash Round Table",
    desc: 'This massive 88" round table is made of solid ash with a custom stain and base for a customer in East Hampton, NY.',
    title: "Eighty-Eight Inch Ash Round Table",
    customer: "res",
    page: 2,
    type: "res-table",
  },
  {
    id: 14,
    src: image14,
    alt: "White Oak Pencil Desk",
    desc: "This desk is made from rift white oak with two drawers for a sleak design",
    title: "White Oak Pencil Desk",
    customer: "res",
    page: 2,
    type: ["res-desk", "cabinetry"],
  },
  {
    id: 15,
    src: image15,
    alt: "Golden Acacia Cookie",
    desc: "This roughly sixty inch round live edge round dining table is hosted within a restaurant in Milan",
    title: "Golden Acacia Cookie",
    customer: "com",
    page: 2,
    type: "com-table",
  },
  {
    id: 16,
    src: image16,
    alt: "Golden Acacia Cookie",
    desc: "This roughly sixty inch round live edge round dining table is hosted within a restaurant in Milan",
    title: "Golden Acacia Cookie",
    customer: "com",
    page: 2,
    type: "com-table",
  },
  {
    id: 17,
    src: image17,
    alt: "Dark Walnut Dining Table",
    desc: "10' Dark Walnut dining table in West Hampton",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 2,
    type: "res-table",
  },
  {
    id: 18,
    src: image18,
    alt: "Golden Acacia Dining Table",
    desc: "This 9' Dark Golden Acacia dining table in West Hampton features custom legs as well as a ceruse finish.",
    title: "Golden Acacia Dining Table",
    customer: "res",
    page: 2,
    type: "res-table",
  },
  {
    id: 19,
    src: image19,
    alt: "White Oak Round",
    desc: "24-Inch round table with tapered legs",
    title: "White Oak Round",
    customer: "res",
    page: 2,
    type: "res-table",
  },
  {
    id: 20,
    src: image20,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 2,
    type: "res-table",
  },

  {
    id: 21,
    src: image21,
    alt: "Golden Acacia Dining Table",
    desc: "This Golden Acacia dining and bench set are located at a residence outside of NYC.",
    title: "Golden Acacia Dining Table",
    customer: "res",
    page: 3,
    type: "res-table",
  },
  {
    id: 22,
    src: image22,
    alt: "Golden Acacia Log",
    desc: "This profile shot features a 1500lbs hollow Golden Acacia log sourced from Thailand. It resides in the backyard of a Chicago suburbian home featuring folding drink rails and a gas firepit.",
    title: "Golden Acacia Log",
    customer: "res",
    page: 3,
    type: "res-deco",
  },
  {
    id: 23,
    src: image23,
    alt: "Dark Acacia Dining Table",
    desc: "This eight foot live edge Acacia table is located in a restaurant in NYC.",
    title: "Dark Acacia Dining Table",
    customer: "com",
    page: 3,
    type: "com-table",
  },
  {
    id: 24,
    src: image24,
    alt: "Dark Acacia Dining Table",
    desc: "A private dining room table with seating for up to twenty people is located in a restaurant in NYC.",
    title: "Dark Acacia Dining Table",
    customer: "com",
    page: 3,
    type: "com-table",
  },
  {
    id: 25,
    src: image25,
    alt: "Dark Acacia Dining Table",
    desc: "This beautiful nine foot live edge Acacia bar seats restaurent patrons feet from the kichen.",
    title: "Dark Acacia Dining Table",
    customer: "com",
    page: 3,
    type: "com-table",
  },
  {
    id: 26,
    src: image26,
    alt: "Golden Acacia Drip Table",
    desc: 'One of our favorite tables to build is the "drip" table carved from the Acacia tree to create a flowing transition to the floor. ',
    title: "Golden Acacia Drip Table",
    customer: "res",
    page: 3,
    type: "res-table",
  },
  {
    id: 27,
    src: image27,
    alt: "Golden Acacia Decorative Mirror",
    desc: "This live edge Acacia mirror is over seven feet tall perfect for any master bedroom.",
    title: "Golden Acacia Decorative Mirror",
    customer: "res",
    page: 3,
    type: "res-deco",
  },
  {
    id: 28,
    src: image28,
    alt: "White Oak Bedside Table",
    desc: "Beautiful white oak bedside table with a natural finish made custom to the customers needs.",
    title: "White Oak Bedside Table",
    customer: "res",
    page: 3,
    type: "res-bed",
  },
  {
    id: 29,
    src: image29,
    alt: "Golden Acacia Dining Table",
    desc: "This large Golden Acacia dining table comfortably seats tweleve people and showcases a beautiful natural finish.",
    title: "Golden Acacia Dining Table",
    customer: "res",
    page: 3,
    type: "res-table",
  },
  {
    id: 30,
    src: image30,
    alt: "Dark Walnut Coffee Table",
    desc: "This custom made Dark Walnut coffee table was made for a residence in New York and features a dark walnut stain.",
    title: "Dark Walnut Coffee Table",
    customer: "res",
    page: 3,
    type: "res-coffee-table",
  },
  {
    id: 31,
    src: image31,
    alt: "Golden Acacia Round Table",
    desc: 'The live edge Golden Acacia Round or "cookie" table is a great way to seat large groups in a small area. This table is located at a restaurant in Miami.',
    title: "Golden Acacia Round Table",
    customer: "com",
    page: 4,
    type: "com-table",
  },
  {
    id: 32,
    src: image32,
    alt: "Cerused White Oak Round",
    desc: 'This 50" round coffee table was custom made and features a cerused finish.',
    title: "Cerused White Oak Round",
    customer: "res",
    page: 4,
    type: "res-table",
  },
  {
    id: 33,
    src: image33,
    alt: "Cerused White Oak Console Table",
    desc: "This custom made console table/desk was made for a customer in Chicago and features a cerused finish.",
    title: "Cerused White Oak Console Table",
    customer: "res",
    page: 4,
    type: ["res-desk", "cabinetry"],
  },
  {
    id: 34,
    src: image34,
    alt: "Walnut Log Reception",
    desc: "Custom carved Walnut log featuring a glass cigar case, brass trim, shelving/storage and a light stain is located at a restaurant in South Florida.",
    title: "Walnut Log Reception Desk",
    customer: "com",
    page: 4,
    type: "com-deco",
  },
  {
    id: 35,
    src: image35,
    alt: "Full Restaurant Build",
    desc: "This image showcases tables, seating, trim, elevated seating and so much more work done with love.",
    title: "Andros Taverna, Chicago IL",
    customer: "com",
    page: 4,
    type: "com-deco",
  },
  {
    id: 36,
    src: image36,
    alt: "Full Restaurant Build",
    desc: "This image showcases tables, seating, trim, elevated seating and so much more work done with love.",
    title: "Andros Taverna, Chicago IL",
    customer: "com",
    page: 4,
    type: "com-deco",
  },
  {
    id: 37,
    src: image37,
    alt: "Golden Acacia Table",
    desc: "This is a nine foot live edge Golden Acacia table featured in a co-working space in Chicago.",
    title: "Golden Acacia Table",
    customer: "com",
    page: 4,
    type: "com-table",
  },
  {
    id: 38,
    src: image38,
    alt: "Ash Round",
    desc: "A close up view on one of many tables made with solid ash and finished with a Dark Walnut stain for a restaurant in downtown Chicago.",
    title: "Ash Round - Finished in Dark Walnut",
    customer: "com",
    page: 4,
    type: "com-table",
  },
  {
    id: 39,
    src: image39,
    alt: "Bathroom Mirrors",
    desc: "Bathroom mirror shadow boxes made for multiple restaurants in Chicago.",
    title: "Vanity Mirrors",
    customer: "com",
    page: 4,
    type: "com-deco",
  },
  {
    id: 40,
    src: image40,
    alt: "Acacia Coffee Table",
    desc: "A beautiful solid Acacia coffee table with matching legs finished using a walnut stain.",
    title: "Acacia Coffee Table - Finished in Dark Walnut Stain",
    customer: "res",
    page: 4,
    type: "res-coffee-table",
  },
  {
    id: 41,
    src: image41,
    alt: "Acacia Dining Table Stained Dark Walnut",
    desc: "This 8 foot custom live edge table features solid Acacia legs and a dark walnut stain.",
    title: "Acacia Dining Table Stained Dark Walnut",
    customer: "res",
    page: 5,
    type: "res-table",
  },
  {
    id: 42,
    src: image42,
    alt: "Solid Ash Book Shelf",
    desc: "This solid ash bookshelf was dreamed up and by the customer and coated with a natural clear finish.",
    title: "Solid Ash Book Shelf",
    customer: "res",
    page: 5,
    type: "res-deco",
  },
  {
    id: 43,
    src: image43,
    alt: "Cerused Ash Coffee Table",
    desc: "This unique coffee table was designed to fit a smaller space and be void of sharp edges. It displays a true cerused finsih made completely of solid ash.",
    title: "Cerused Ash Coffee Table",
    customer: "res",
    page: 5,
    type: "res-coffee-table",
  },
  {
    id: 44,
    src: image44,
    alt: "26' Acacia Live Edge Dining Table",
    desc: "Massive live edge Acacia dining table for a customer outside of Boston, MA. This table features a natural finsih and custom metal legs.",
    title: "26' Acacia Live Edge Dining Table",
    customer: "res",
    page: 5,
    type: "res-table",
  },
  {
    id: 45,
    src: image45,
    alt: "Rift White Oak Pencil Desk",
    desc: "Rift white oak veneer pencil desk with dual drawers for a customer in East Hampton, NY. Finished with a clear natural sealant.",
    title: "Rift White Oak Pencil Desk",
    customer: "res",
    page: 5,
    type: ["res-desk", "cabinetry"],
  },
  {
    id: 46,
    src: image46,
    alt: "Acacia Live Edge Table",
    desc: "Custom size live edge Acacia conference table for an office in New York City.",
    title: "Acacia Live Edge Table",
    customer: "com",
    page: 5,
    type: "com-table",
  },
  {
    id: 47,
    src: image47,
    alt: "Ash Strip Bench",
    desc: "12' bench made of metal and ash slats for a restaurant in Chicago. We manufactured over 30 of these benches to fill the restaurant.",
    title: "Ash Slat Bench",
    customer: "com",
    page: 5,
    type: "com-deco",
  },
  {
    id: 48,
    src: image48,
    alt: "Figured Maple Live Edge Dining Table",
    desc: "A custom live edge Maple dining table cut into three sections to allow for multiple seating options. This table was installed at a customers home in Aspen, CO.",
    title: "Figured Maple Live Edge Dining Table",
    customer: "res",
    page: 5,
    type: ["res-table"],
  },
  {
    id: 49,
    src: image49,
    alt: "Dark Walnut Bed Frame and Headboard",
    desc: "A view of the floating bed frame, head board and side tables made from solid dark walnut for a customer in Aspen, CO.",
    title: "Dark Walnut Bed Frame and Headboard",
    customer: "res",
    page: 5,
    type: ["res-bed"],
  },
  {
    id: 50,
    src: image50,
    alt: "Dark Walnut Headboard",
    desc: "A shot of a dark walnut headboard before being crane lifted into a third story of a home in Aspen, CO.",
    title: "Dark Walnut Headboard",
    customer: "res",
    page: 5,
    type: ["res-bed"],
  },
  {
    id: 51,
    src: image51,
    alt: "Shou Sugi Ban Desk and Drawers",
    desc: "A custom floating desk made from Ash and finished in true sho sugi ban style by burning the wood to a crisp.",
    title: "Shou Sugi Ban Desk and Drawers",
    customer: "res",
    page: 6,
    type: ["res-desk", "cabinetry"],
  },
  {
    id: 52,
    src: image52,
    alt: "Dark Walnut Bedroom Set",
    desc: "Custom floating dark walnut bed frame with built-in side tables.",
    title: "Dark Walnut Bedroom Set",
    customer: "res",
    page: 6,
    type: ["res-bed", "cabinetry"],
  },
  {
    id: 53,
    src: image53,
    alt: "Dark Walnut Bedroom Set",
    desc: "Custom dark walnut headboard made of three live-edge walnut slabs with a floating dark walnut frame. The Sidetables are made metal and walnut custom made for our client.",
    title: "Dark Walnut Bedroom Set",
    customer: "res",
    page: 6,
    type: ["res-bed", "cabinetry"],
  },
  {
    id: 54,
    src: image54,
    alt: "Solid White Washed Bed Side Tables",
    desc: "Custom made solid end tables made a white wash finish for a customer in East Hampton, NY.",
    title: "Solid White Washed Bed Side Tables",
    customer: "res",
    page: 6,
    type: ["res-bed", "cabinetry"],
  },
  {
    id: 55,
    src: image55,
    alt: "Rift White Oak Pencil Desk",
    desc: "Rift white oak veneer pencil desk with dual drawers for a customer in East Hampton, NY. Finished with a clear natural sealant.",
    title: "Rift White Oak Pencil Desk",
    customer: "res",
    page: 6,
    type: ["res-desk", "cabinetry"],
  },
  {
    id: 56,
    src: image56,
    alt: "Rustic Oak Dining Table",
    desc: "A rustic farm style table made from reclaimed oak for a private dining room in a Chicago restaurant.",
    title: "Rustic Oak Dining Table",
    customer: "com",
    page: 6,
    type: "com-table",
  },
  {
    id: 57,
    src: image57,
    alt: "Solid Ash Coffee Table",
    desc: "Custom desinged coffee table by the customer made in solid Ash and finished with a walnut stain.",
    title: "Solid Ash Coffee Table",
    customer: "res",
    page: 6,
    type: "res-coffee-table",
  },
  {
    id: 58,
    src: image58,
    alt: "Reclaimed Leeche Root Trophy Base",
    desc: "This root was found at the bottom of a river in Thailand and repurposed here to display the customers brass sculpsure.",
    title: "Reclaimed Leeche Root Trophy Base",
    customer: "res",
    page: 6,
    type: "res-deco",
  },
  //Need to update desc info from here on
  {
    id: 59,
    src: image59,
    alt: "Built In Storage Closet",
    desc: "Custom built in under stair storage unit for a customer in Chicago, Il. Utilizing the empty space under the stairs we generated storage for coats, shoes and even a custom liquor shelf.",
    title: "Built In Storage Closet",
    customer: "res",
    page: 6,
    type: ["cabinetry"],
  },
  {
    id: 60,
    src: image60,
    alt: "Built In Storage Closet",
    desc: "Custom built in under stair storage unit for a customer in Chicago, Il. Utilizing the empty space under the stairs we generated storage for coats, shoes and even a custom liquor shelf.",
    title: "Built In Storage Closet",
    customer: "res",
    page: 6,
    type: ["cabinetry"],
  },
  {
    id: 61,
    src: image61,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 62,
    src: image62,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 63,
    src: image63,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 64,
    src: image64,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 65,
    src: image65,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 66,
    src: image66,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 67,
    src: image67,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 68,
    src: image68,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 69,
    src: image69,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 70,
    src: image70,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 7,
  },
  {
    id: 71,
    src: image71,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 72,
    src: image72,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 73,
    src: image73,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 74,
    src: image74,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 75,
    src: image75,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 76,
    src: image76,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 77,
    src: image77,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 78,
    src: image78,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 79,
    src: image79,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 80,
    src: image80,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 8,
  },
  {
    id: 81,
    src: image81,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 9,
  },
  {
    id: 82,
    src: image82,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 9,
  },
  {
    id: 83,
    src: image83,
    alt: "Dark Walnut Dining Table",
    desc: "This is a close up shot of the beautiful figuring on a 9 foot dark walnut dining table.",
    title: "Dark Walnut Dining Table",
    customer: "res",
    page: 9,
  },
];
export default imageData;
